### ISSUE TITLE
Unit test with OAuth

### ISSUE THREAD

**Issue by llaine** [seegno/angular-oauth2#53]
Hi,
i'm trying to test a controller which use `OAuth.isAuthenticated()` and `OAuth.getAccessToken()`, 
but while trying to mock the OAuth module i'm getting the same error. 

```
Error: `OAuthProvider` must be configured first.
    at new OAuth (http://localhost:8080/base/app/bower_components/angular-oauth2/dist/angular-oauth2.js:85:31)
    at OAuthProvider.$get (http://localhost:8080/base/app/bower_components/angular-oauth2/dist/angular-oauth2.js:173:20)
    at Object.invoke (http://localhost:8080/base/app/bower_components/angular/angular.js:4426:17)
    at http://localhost:8080/base/app/bower_components/angular/angular.js:4244:37
    at getService (http://localhost:8080/base/app/bower_components/angular/angular.js:4385:39)
    at Object.invoke (http://localhost:8080/base/app/bower_components/angular/angular.js:4417:13)
    at http://localhost:8080/base/app/bower_components/angular/angular.js:4248:71
    at forEach (http://localhost:8080/base/app/bower_components/angular/angular.js:336:20)
    at Object.createInjector [as injector] (http://localhost:8080/base/app/bower_components/angular/angular.js:4248:3)
    at Object.workFn (http://localhost:8080/base/app/bower_components/angular-mocks/angular-mocks.js:2409:52)
```

Here my test : 

```javascript

describe('MyCtrl', function() {
  var $scope;
  var OAuth;

  beforeEach(module('App.auth'));

  beforeEach(function() {

    var mockOAuth = {};
    inject(function($q) {
      /* angular-oauth2 OAuth mock */
      mockOAuth.accessToken = 'toto';
      mockOAuth.getAccessToken = function(credentials) {
        var self = this;
        var defer = $q.defer();
        defer.resolve(self.accessToken);
        return defer.promise;
      };

      mockOAuth.isAuthenticated = function() {
        return !!this.accessToken;
      };

      mockOAuth.setToken = function(token) {
        this.accessToken = token;
      };
    });

    module('App.auth', function($provide) {
      $provide.value('OAuth', mockOAuth);
    });

  });


  beforeEach(inject(function(_$controller_, _$rootScope_, _OAuth_) {

    $scope = _$rootScope_.$new();
    OAuth = _OAuth_;

    _$controller_('App.authController', {
      $scope:$scope,
      OAuth:OAuth
    });

    $scope.$digest();

  }));


  it('spec', function () {
  // Getting the error while no test specs. 
  });
```

And here is the controller 

```javascript 
angular.module('App.auth')
  .controller('App.authController', [
		'$scope', '$http', '$route', '$location', '$localStorage', 'OAuth',
		function($scope, $http, $route, $location, $localStorage, OAuth) {
   
    $scope.login = function(credentials) {
      //on appelle l'url permettant de s'authentifier
      OAuth.getAccessToken(credentials)
        .then(function(/*token*/) {
         // ...
        });
    };

    
    if (OAuth.isAuthenticated()) {
      // ...
    } else {
      // ...
    }
  }]);




```

**Comment by joaogranado** [comment]
Hi @llaine! The main issue here relies on the fact that `OAuthProvider` requires initial configuration. You should address this in a PR by providing a mocked version of it. For now you could do this by injecting it using `module` on the `beforeEach` hook and configure it by your own, such as:

```js
beforeEach(module(function(_OAuthProvider_) {
  _OAuthProvider_.configure({
      baseUrl: 'https://api.website.com',
      clientId: 'CLIENT_ID',
      clientSecret: 'CLIENT_SECRET' // optional
    });
}));
```

I might be missing something here but the problem should be solved by configuring it this way.

**Comment by llaine** [comment]
Hi @joaogranado, thank you for answering! 
I managed to fix the problem, here is my solution : 


```javascript
// ...
 beforeEach(function() {
    var mockOAuth = {};

    inject(function($q, OAuth) {
      /* mock du angular-oauth2 */
      mockOAuth.accessToken = 'toto';
      /**
       *
       * @param credentials
       * @returns {*}
       */
      mockOAuth.getAccessToken = function(credentials) {
        if (!credentials || !credentials.username || !credentials.password) {
          throw 'Credentials non définis';
        }
        var self = this;
        var defer = $q.defer();
        defer.resolve(self.accessToken);
        return defer.promise;
      };

      /**
       *
       * @returns {boolean}
       */
      mockOAuth.isAuthenticated = function() {
        return !!this.accessToken;
      };

      /**
       *
       * @param token
       */
      mockOAuth.setToken = function(token) {
        this.accessToken = token;
      };
      
      /* just mocking two function */
      OAuth.getAccessToken = mockOAuth.getAccessToken;
      OAuth.isAuthenticated = mockOAuth.isAuthenticated;
      oAuth = OAuth;
    });
  });
// ...
```
